DEBUG: false
# Debug_freq is steps (num iters)
LOGDIR: '' 
DEVICE: 'cuda'
EXP_NAME: 'vibe'
OUTPUT_DIR: 'results/tests'
NUM_WORKERS: 0
SEED_VALUE: -1
MODEL:
  TEMPORAL_TYPE: 'gru'
  TGRU:
    NUM_LAYERS: 2
    ADD_LINEAR: true
    RESIDUAL: true
    BIDIRECTIONAL: false
    HIDDEN_SIZE: 1024
  BACKBONE_CKPT: 'data/vpare_data/hrnet_w32.pth.tar'
  PRETRAINED_PARE: 'data/vpare_data/pare_w_3dpw_checkpoint.ckpt'
  USE_PART_ATT: true
  USE_POSE_TGRU: false
  USE_SC_TGRU: false
  USE_MAX_ENCODER: true
DATASET:
  SEQLEN: 48
LOSS:
  KP_2D_W: 300.0
  KP_3D_W: 300.0
  SHAPE_W: 0.06
  POSE_W: 60.0
  E_MOTION_LOSS_W: 0.5
  D_MOTION_LOSS_R: 1.0
TRAIN:
  MODE: 0
  BATCH_SIZE: 32
  NUM_ITERS_PER_EPOCH: 20
  PRETRAINED: 'data/vibe_data/vibe_model_w_3dpw.pth.tar' #'data/vibe_data/vibe_wgagl.pth.tar'
  PRETRAINED_REGRESSOR: 'data/vibe_data/spin_model_checkpoint.pth.tar'
  RESUME: ''  
  START_EPOCH: 0
  END_EPOCH: 10
  LR_PATIENCE: 5
  DATA_2D_RATIO: 0.
  GEN_LR: 0.00005
  GEN_WD: 0.0
  MOT_DISCR:
    OPTIM: 'Adam'
    LR: 0.0001
    WD: 0.0001
    MOMENTUM: 0.9
    HIDDEN_SIZE: 1024
    NUM_LAYERS: 2
    FEATURE_POOL: 'attention'
    ATT:
      LAYERS: 3
      SIZE: 1024
      DROPOUT: 0.2