LOGDIR: '' 
DEVICE: 'cuda'
EXP_NAME: 'grnet'
OUTPUT_DIR: 'results/tests'
NUM_WORKERS: 0
SEED_VALUE: -1
MODEL:
  BACKBONE_CKPT: 'data/grnet_data/hrnet_w32.pth.tar'
  PRETRAINED_PARE: 'data/grnet_data/pare_w_3dpw_checkpoint.ckpt'
  FEAT_CORR:
    AVG_DIM: 3
    ESTIM_PHASE: true
    NUM_LAYERS: 1
    H_SIZE: 1024
    USE_JWFF: true
    NUM_HEADS: 4
DATASET:
  SEQLEN: 100